version: "3.9"

services:
  app:
    build: .
    container_name: php-apache
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
      - ./logs:/var/www/html/logs
    environment:
      - PGHOST=nozomi.proxy.rlwy.net
      - PGPORT=55963
      - PGDATABASE=railway
      - PGUSER=postgres
      - PGPASSWORD=kDPxQveFCjClOVCFFZlrAiTsEWfWWJQu
      - PORT=8080
    networks:
      - app-network

# ELIMINAR completamente el servicio de base de datos local
networks:
  app-network:
    driver: bridge